### ISSUE TITLE
Kick Off - Creating a CRUD application in Go

### ISSUE THREAD

**Issue by DhirenB94** [DhirenB94/nfon-crud#1]
### Create a CRUD service with Golang:
Your task is to develop a simple CRUD service in Golang for managing items. Each item should have a unique ID and a name. The service should support the following operations:

1) Create Item: Add a new item to the system.
2) Get Item by ID: Retrieve an item by its ID.
3) Get All Items: Retrieve all items. Additionally, implement a query parameter to filter items by name.
4) Update Item: Modify an existing item by its ID.
5) Delete Item: Remove an item from the system.

### Task Breakdown
```
Given a item management service
When any CRUD operation is performed
Then the service should successfully execute the operations
```
- [x] Create a basic http sever and handler with unit tests ensuring a status 200
- [x] Add an item storage interface and add this as a dependency when creating a new server
- [x] Create a router and define the routes with corresponding handlers (blank for now)
- [x] Define a data model for the items
- [x] Define the methods for the CRUD service in the interface
- [x] Create a mock item store to allow the server to be tested
- [x] Logic and unit tests for createItem handler
- [x] Logic and unit tests for getAllItems handler
- [x] Logic and unit tests for the manageItem handler
        - GetItemByID
        - UpdateItem
        - DeleteItem
- [x] Write integration test for inMemDB (failing at first)
- [x] Create inMemDB methods with unit tests
- [x] Use the inMemDB in main and pass the integration tests

Error Handling
1.  Return error when the ID does not exist in the memory store
2. Allow GetAllItems to return no items (not an error) when no name is passed, but error when name is passed and does not exist in the memory store
